version: "3"
services:
  db:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=haven_db

    volumes:
      - ./haven_db:/var/lib/postgresql/data
    # Mapping the port 6000 on the host to the port 5432 on the container
    ports:
      - "6000:5432"
    networks:
      - webnet
  # Specifications for the frontend service
  frontend:
    build:
      # Sets the context to the current directory thos docker-compose yml file is placed in
      context: ./Docker

      # Specfying the Dockerfile for building the frontend image
      dockerfile: frontend.dockerfile

    # Mapping the port 3110 on the host to the port 3110 on the container
    ports:
      - "3110:3110"
    
    # defining the networking of the container
    networks:
      - webnet
  
  # Specifications for the backend service
  backend:
    build:
      # Sets the context to the current directory thos docker-compose yml file is placed in
      context: ./Docker
      # Specfies the Dockerfile for building the backend image
      dockerfile: backend.dockerfile

    # Mapping the port 4000 on the host to the port 4000 on the container
    ports:
      - "4000:4000"

    depends_on:
      - db
    
    # defining the networking of the container
    networks:
      - webnet


networks:
  webnet:

