apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timmy-lms-postgres
  labels:
    name: timmy-lms-database
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: timmy-lms-postgres
    spec:
      containers:
      - name: timmy-lms-postgres
        image: postgres:10.5-alpine
        volumeMounts:
        - name: timmy-lms-postgres-volume-mount
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: timmy-lms-postgres-credentials
              key: user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: timmy-lms-postgres-credentials
              key: db_name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timmy-lms-postgres-credentials
              key: password
      restartPolicy: Always
      volumes:
      - name: timmy-lms-postgres-volume-mount
        persistentVolumeClaim:
          claimName: timmy-lms-postgres-pvc
