apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timmy-lms-postgres-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: timmy-lms-postgres-pv
