apiVersion: v1
kind: PersistentVolume
metadata:
  name: timmy-lms-postgres-pv
  labels:
    name: timmy-lms-postgres-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: timmy-lms-pg-data-disk
    fsType: ext4
